[package]
name = "database"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[dependencies]
config.workspace = true
appstate.workspace = true
tokio.workspace = true
rusqlite.workspace = true